spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqrs
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true

# my app update every second “token_entry set timestamp=? where processor_name=? and segment=? and owner=?”
# it does’t stop still rerun again. I don't know what I can do to stop the update and my app become stable ::
# Ans => The update token entry are completely normal, they prevent the token is stolen by an other possible instance.
# The default for the tracking event processor, is to do this every second.